version: '3.8'

services:
  app:
    build: .
    container_name: daily-hot-reminder
    environment:
      RUN_AS_SCHEDULER: true
      # 数据库配置
      SQLALCHEMY_DATABASE_URL: postgresql://root:root@host.docker.internal:5432/alfred
      SUMMARIZER_API_URL: ${SUMMARIZER_API_URL}
      # 邮件配置
      SMTP_SERVER: ${SMTP_SERVER}
      SMTP_PORT: ${SMTP_PORT}
      SENDER_EMAIL: ${SENDER_EMAIL}
      SENDER_PASSWORD: ${SENDER_PASSWORD}
      # 收件人配置
      RECIPIENT_yueyong1030@outlook.com: 36kr,tieba,zhihu
    extra_hosts:
      - "host.docker.internal:host-gateway"   # Linux 需要；mac/win 可保留无害
    env_file:
      - .env
    dns:
      - 8.8.8.8
      - 1.1.1.1
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped