version: '3.8'

services:
  app:
    build: .
    container_name: daily_hot_reminder
    environment:
      RUN_AS_SCHEDULER: true
      # 数据库配置
      DATABASE_URL: postgresql://root:root@host.docker.internal:5432/alfred
      # 邮件配置
      SMTP_SERVER: ${SMTP_SERVER}
      SMTP_PORT: ${SMTP_PORT}
      SENDER_EMAIL: ${SENDER_EMAIL}
      SENDER_PASSWORD: ${SENDER_PASSWORD}
      # 收件人配置
      RECIPIENT_yueyong1030@outlook.com: 36kr,tieba,zhihu
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped